name: Build, Push, and Deploy via SSH

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vhs-rentals:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/vhs-rentals:${{ github.sha }}

      # 4) SSH deploy to VPS
      - name: Deploy to VPS via SSH
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            set -e
            cd /home/deploy/myapp
            docker compose pull
            docker compose up -d --remove-orphans
            sleep 3
            docker compose ps